import json
import os
from pathlib import Path

from dotenv import load_dotenv
from langchain_google_genai import ChatGoogleGenerativeAI
from pydantic import BaseModel, Field


MODEL_NAME = "gemini-3.5-flash-lite"

PROMPT_PATH = (
    Path(__file__).resolve().parent.parent
    / "prompts"
    / "con_prompt.txt"
)


class ConArgument(BaseModel):
    """Structured response generated by the Con Agent."""

    position: str = Field(
        description="The debate position, which must be con."
    )

    opening_statement: str = Field(
        description="A concise opening statement opposing the topic."
    )

    arguments: list[str] = Field(
        min_length=3,
        max_length=3,
        description="Exactly three distinct arguments opposing the topic.",
    )

    conclusion: str = Field(
        description="A concise conclusion opposing the topic."
    )


def load_con_prompt() -> str:
    """Load the Con Agent instructions from its prompt file."""

    if not PROMPT_PATH.exists():
        raise FileNotFoundError(
            f"Con prompt was not found: {PROMPT_PATH}"
        )

    prompt = PROMPT_PATH.read_text(encoding="utf-8").strip()

    if not prompt:
        raise ValueError("The Con prompt file is empty.")

    return prompt


def _clean_required_text(value: str, field_name: str) -> str:
    """Validate and normalize a required text value."""

    if not isinstance(value, str):
        raise TypeError(f"{field_name} must be a string.")

    cleaned_value = " ".join(value.split())

    if not cleaned_value:
        raise ValueError(f"{field_name} cannot be empty.")

    if len(cleaned_value) < 5:
        raise ValueError(f"{field_name} is too short.")

    return cleaned_value


def validate_con_inputs(
    topic: str,
    con_instruction: str,
) -> tuple[str, str]:
    """Validate the topic and Moderator instruction."""

    cleaned_topic = _clean_required_text(
        topic,
        "The debate topic",
    )

    cleaned_instruction = _clean_required_text(
        con_instruction,
        "The Con Agent instruction",
    )

    return cleaned_topic, cleaned_instruction


def create_con_model():
    """Create the Gemini model with structured output."""

    load_dotenv()

    if not os.getenv("GOOGLE_API_KEY"):
        raise EnvironmentError(
            "GOOGLE_API_KEY was not found in the .env file."
        )

    model = ChatGoogleGenerativeAI(
        model=MODEL_NAME,
        max_retries=4,
    )

    return model.with_structured_output(
        schema=ConArgument.model_json_schema(),
        method="json_schema",
    )


def generate_con_argument(
    topic: str,
    con_instruction: str,
) -> dict:
    """Generate arguments opposing the debate topic."""

    cleaned_topic, cleaned_instruction = validate_con_inputs(
        topic,
        con_instruction,
    )

    con_prompt = load_con_prompt()
    structured_model = create_con_model()

    try:
        result = structured_model.invoke(
            [
                ("system", con_prompt),
                (
                    "human",
                    (
                        f"Debate topic: {cleaned_topic}\n"
                        f"Moderator instruction: {cleaned_instruction}\n"
                        "Your position is con."
                    ),
                ),
            ]
        )
    except Exception as error:
        raise RuntimeError(
            f"The Con Agent could not generate its argument: {error}"
        ) from error

    validated_result = ConArgument.model_validate(result)

    if validated_result.position.strip().lower() != "con":
        raise ValueError(
            "The Con Agent returned an invalid debate position."
        )

    validated_result.position = "con"

    return validated_result.model_dump()


if __name__ == "__main__":
    sample_topic = (
        "Should artificial intelligence replace human teachers "
        "in education?"
    )

    sample_instruction = (
        "Present arguments opposing the replacement of human "
        "teachers with artificial intelligence."
    )

    con_response = generate_con_argument(
        sample_topic,
        sample_instruction,
    )

    print("\nCon Agent output:\n")
    print(json.dumps(con_response, indent=2))