import json
import os
from pathlib import Path

from dotenv import load_dotenv
from langchain_google_genai import ChatGoogleGenerativeAI
from pydantic import BaseModel, Field


MODEL_NAME = "gemini-3.5-flash-lite"

PROMPT_PATH = (
    Path(__file__).resolve().parent.parent
    / "prompts"
    / "pro_prompt.txt"
)


class ProArgument(BaseModel):
    """Structured response generated by the Pro Agent."""

    position: str = Field(
        description="The debate position, which must be pro."
    )

    opening_statement: str = Field(
        description="A concise opening statement supporting the topic."
    )

    arguments: list[str] = Field(
        min_length=3,
        max_length=3,
        description="Exactly three distinct arguments supporting the topic.",
    )

    conclusion: str = Field(
        description="A concise conclusion supporting the topic."
    )


def load_pro_prompt() -> str:
    """Load the Pro Agent instructions from its prompt file."""

    if not PROMPT_PATH.exists():
        raise FileNotFoundError(
            f"Pro prompt was not found: {PROMPT_PATH}"
        )

    prompt = PROMPT_PATH.read_text(encoding="utf-8").strip()

    if not prompt:
        raise ValueError("The Pro prompt file is empty.")

    return prompt


def _clean_required_text(value: str, field_name: str) -> str:
    """Validate and normalize a required text value."""

    if not isinstance(value, str):
        raise TypeError(f"{field_name} must be a string.")

    cleaned_value = " ".join(value.split())

    if not cleaned_value:
        raise ValueError(f"{field_name} cannot be empty.")

    if len(cleaned_value) < 5:
        raise ValueError(f"{field_name} is too short.")

    return cleaned_value


def validate_pro_inputs(
    topic: str,
    pro_instruction: str,
) -> tuple[str, str]:
    """Validate the topic and Moderator instruction."""

    cleaned_topic = _clean_required_text(topic, "The debate topic")
    cleaned_instruction = _clean_required_text(
        pro_instruction,
        "The Pro Agent instruction",
    )

    return cleaned_topic, cleaned_instruction


def create_pro_model():
    """Create the Gemini model with structured output."""

    load_dotenv()

    if not os.getenv("GOOGLE_API_KEY"):
        raise EnvironmentError(
            "GOOGLE_API_KEY was not found in the .env file."
        )

    model = ChatGoogleGenerativeAI(
        model=MODEL_NAME,
        max_retries=4,
    )

    return model.with_structured_output(
        schema=ProArgument.model_json_schema(),
        method="json_schema",
    )


def generate_pro_argument(
    topic: str,
    pro_instruction: str,
) -> dict:
    """Generate arguments supporting the debate topic."""

    cleaned_topic, cleaned_instruction = validate_pro_inputs(
        topic,
        pro_instruction,
    )

    pro_prompt = load_pro_prompt()
    structured_model = create_pro_model()

    try:
        result = structured_model.invoke(
            [
                ("system", pro_prompt),
                (
                    "human",
                    (
                        f"Debate topic: {cleaned_topic}\n"
                        f"Moderator instruction: {cleaned_instruction}\n"
                        "Your position is pro."
                    ),
                ),
            ]
        )
    except Exception as error:
        raise RuntimeError(
            f"The Pro Agent could not generate its argument: {error}"
        ) from error

    validated_result = ProArgument.model_validate(result)

    if validated_result.position.strip().lower() != "pro":
        raise ValueError(
            "The Pro Agent returned an invalid debate position."
        )

    validated_result.position = "pro"

    return validated_result.model_dump()


if __name__ == "__main__":
    sample_topic = (
        "Should artificial intelligence replace human teachers "
        "in education?"
    )

    sample_instruction = (
        "Present arguments supporting the replacement of human "
        "teachers with artificial intelligence."
    )

    pro_response = generate_pro_argument(
        sample_topic,
        sample_instruction,
    )

    print("\nPro Agent output:\n")
    print(json.dumps(pro_response, indent=2))