import json
import os
from pathlib import Path

from dotenv import load_dotenv
from langchain_google_genai import ChatGoogleGenerativeAI
from pydantic import BaseModel, Field


MODEL_NAME = "gemini-3.5-flash-lite"

PROMPT_PATH = (
    Path(__file__).resolve().parent.parent
    / "prompts"
    / "rebuttal_prompt.txt"
)

REQUIRED_ARGUMENT_FIELDS = {
    "position",
    "opening_statement",
    "arguments",
    "conclusion",
}


class RebuttalResponse(BaseModel):
    """Structured response generated by the Rebuttal Agent."""

    pro_rebuttals: list[str] = Field(
        min_length=2,
        max_length=2,
        description=(
            "Exactly two Pro rebuttals responding to the Con arguments."
        ),
    )

    con_rebuttals: list[str] = Field(
        min_length=2,
        max_length=2,
        description=(
            "Exactly two Con rebuttals responding to the Pro arguments."
        ),
    )


def load_rebuttal_prompt() -> str:
    """Load the Rebuttal Agent instructions from its prompt file."""

    if not PROMPT_PATH.exists():
        raise FileNotFoundError(
            f"Rebuttal prompt was not found: {PROMPT_PATH}"
        )

    prompt = PROMPT_PATH.read_text(encoding="utf-8").strip()

    if not prompt:
        raise ValueError("The Rebuttal prompt file is empty.")

    return prompt


def _clean_topic(topic: str) -> str:
    """Validate and normalize the debate topic."""

    if not isinstance(topic, str):
        raise TypeError("The debate topic must be a string.")

    cleaned_topic = " ".join(topic.split())

    if not cleaned_topic:
        raise ValueError("The debate topic cannot be empty.")

    if len(cleaned_topic) < 5:
        raise ValueError("The debate topic is too short.")

    return cleaned_topic


def _validate_argument(
    argument: dict,
    expected_position: str,
) -> dict:
    """Validate an argument received from a debate agent."""

    if not isinstance(argument, dict):
        raise TypeError(
            f"The {expected_position} argument must be a dictionary."
        )

    if not argument:
        raise ValueError(
            f"The {expected_position} argument cannot be empty."
        )

    missing_fields = REQUIRED_ARGUMENT_FIELDS - argument.keys()

    if missing_fields:
        missing_text = ", ".join(sorted(missing_fields))

        raise ValueError(
            f"The {expected_position} argument is missing: "
            f"{missing_text}."
        )

    position = argument["position"]

    if not isinstance(position, str):
        raise TypeError(
            f"The {expected_position} position must be a string."
        )

    if position.strip().lower() != expected_position:
        raise ValueError(
            f"Expected a {expected_position} argument, "
            f"but received position '{position}'."
        )

    if not isinstance(argument["arguments"], list):
        raise TypeError(
            f"The {expected_position} arguments field must be a list."
        )

    if not argument["arguments"]:
        raise ValueError(
            f"The {expected_position} arguments list cannot be empty."
        )

    return argument


def validate_rebuttal_inputs(
    topic: str,
    pro_argument: dict,
    con_argument: dict,
) -> tuple[str, dict, dict]:
    """Validate all inputs required by the Rebuttal Agent."""

    cleaned_topic = _clean_topic(topic)
    validated_pro = _validate_argument(pro_argument, "pro")
    validated_con = _validate_argument(con_argument, "con")

    return cleaned_topic, validated_pro, validated_con


def create_rebuttal_model():
    """Create the Gemini model with structured output."""

    load_dotenv()

    if not os.getenv("GOOGLE_API_KEY"):
        raise EnvironmentError(
            "GOOGLE_API_KEY was not found in the .env file."
        )

    model = ChatGoogleGenerativeAI(
        model=MODEL_NAME,
        max_retries=4,
    )

    return model.with_structured_output(
        schema=RebuttalResponse.model_json_schema(),
        method="json_schema",
    )


def generate_rebuttals(
    topic: str,
    pro_argument: dict,
    con_argument: dict,
) -> dict:
    """Generate rebuttals for both sides of the debate."""

    cleaned_topic, validated_pro, validated_con = (
        validate_rebuttal_inputs(
            topic,
            pro_argument,
            con_argument,
        )
    )

    rebuttal_prompt = load_rebuttal_prompt()
    structured_model = create_rebuttal_model()

    try:
        result = structured_model.invoke(
            [
                ("system", rebuttal_prompt),
                (
                    "human",
                    (
                        f"Debate topic:\n{cleaned_topic}\n\n"
                        f"Pro argument:\n"
                        f"{json.dumps(validated_pro, indent=2)}\n\n"
                        f"Con argument:\n"
                        f"{json.dumps(validated_con, indent=2)}"
                    ),
                ),
            ]
        )
    except Exception as error:
        raise RuntimeError(
            f"The Rebuttal Agent could not respond: {error}"
        ) from error

    validated_result = RebuttalResponse.model_validate(result)

    return validated_result.model_dump()


if __name__ == "__main__":
    sample_topic = (
        "Should artificial intelligence replace human teachers "
        "in education?"
    )

    sample_pro_argument = {
        "position": "pro",
        "opening_statement": (
            "AI can make education more accessible and personalized."
        ),
        "arguments": [
            "AI can adapt lessons to individual learning speeds.",
            "AI educational systems can operate at any time.",
            "AI can reduce repetitive administrative work.",
        ],
        "conclusion": (
            "AI can provide scalable and individualized education."
        ),
    }

    sample_con_argument = {
        "position": "con",
        "opening_statement": (
            "Human teachers remain essential to effective education."
        ),
        "arguments": [
            "Teachers provide empathy and emotional support.",
            "AI may reproduce errors and bias.",
            "Not every student has reliable access to technology.",
        ],
        "conclusion": (
            "AI should assist teachers rather than replace them."
        ),
    }

    response = generate_rebuttals(
        sample_topic,
        sample_pro_argument,
        sample_con_argument,
    )

    print("\nRebuttal Agent output:\n")
    print(json.dumps(response, indent=2))